#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Clean reference images produced for a certain category(refs_clean, Right nowcc0reviewThe batch of pictures shown)Do portrait clustering(GPU)。
usage: python cluster_refs_category.py <category> [--sim-thr 0.55]
Output to the scene board as the basis for actor grouping. threshold decision(2026-07-10): 0.42 People with similar looks will be linked together
String into medium-sized groups(Avoid the billboard MAX_GROUP=12/MIN_SIM=0.32 line of defense)Resulting in over-merging of scenes and mixing of people inside,
Set as 0.55 It's better to be careful than to mix things up - scene fragments can be "merged into scenes" on the billboardx"Manual merge, It's mixed and can't be taken apart.
wrestle_grapple use 0.42 The version has been manually finalized, No repeat runs.
output: ~/ref_clusters_<category>.json  (Return the actor confirmation page generated by the development machine)
"""
import argparse, json, os
from pathlib import Path
import cv2
import numpy as np
from insightface.app import FaceAnalysis

ap = argparse.ArgumentParser()
ap.add_argument("category")
ap.add_argument("--sim-thr", type=float, default=0.55)
args = ap.parse_args()

BASE = Path(os.environ.get("BASE_DIR", str(Path.home())))
refs = []
for shard in sorted((BASE / "mpie_data" / "cc0_full").glob(f"{args.category}_shard*")):
    refs += sorted((shard / "refs_clean").glob("*.jpg"))
if not refs:
    raise SystemExit(f"Not found {args.category} of refs_clean picture, examine {BASE}/mpie_data/cc0_full/")
print(f"{args.category}: {len(refs)} Reference picture")

fa = FaceAnalysis(name="antelopev2", providers=["CUDAExecutionProvider"])
fa.prepare(ctx_id=0, det_size=(640, 640))

embs, names, no_face = [], [], []
for i, p in enumerate(refs):
    img = cv2.imread(str(p))
    faces = fa.get(img) if img is not None else []
    if faces:
        f = max(faces, key=lambda f: (f.bbox[2]-f.bbox[0])*(f.bbox[3]-f.bbox[1]))
        embs.append(f.normed_embedding)
        names.append(p.name)
    else:
        no_face.append(p.name)
    if (i + 1) % 100 == 0:
        print(f"  {i+1}/{len(refs)}")

print(f"Have a face {len(names)} / Shameless {len(no_face)}, Clustering...")
X = np.stack(embs)
sim = X @ X.T

parent = list(range(len(names)))
def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x
for i in range(len(names)):
    for j in range(i + 1, len(names)):
        if sim[i, j] >= args.sim_thr:
            parent[find(i)] = find(j)

comps = {}
for i in range(len(names)):
    comps.setdefault(find(i), []).append(i)

groups = []
for members in comps.values():
    avg = 1.0
    if len(members) > 1:
        vals = [sim[a, b] for k, a in enumerate(members) for b in members[k+1:]]
        avg = float(np.mean(vals))
    groups.append({
        "avg_sim": round(avg, 3),
        "members": [{"video_id": names[i].split("_r")[0], "thumb": names[i]} for i in sorted(members)],
    })
groups.sort(key=lambda g: -len(g["members"]))

out = BASE / f"ref_clusters_{args.category}.json"
out.write_text(json.dumps({"groups": groups, "no_face": no_face}, ensure_ascii=False, indent=1))
n_multi = sum(1 for g in groups if len(g["members"]) > 1)
print(f"Finish: {len(groups)} Group(Multiple picture groups{n_multi}/Single picture group{len(groups)-n_multi}), Shameless{len(no_face)} -> {out}")